#!/bin/bash
msglog="/var/log/update_prod.log"
log()
{
        echo "$(date) ${1:-missing}" >> $msglog
}
cd ~/web/htdocs
log "------------ Update PROD ------------"
git=`git pull | tee -a $msglog`
[[ "$git" =~ "Already up-to-date" ]]  || /usr/local/bin/gulp deploy --prod &>> $msglog
log "-------------------------------------"
exit 0
