#!/bin/bash
lock=/tmp/update_prod.lock
msglog="/var/log/update_prod.log"
log()
{
        echo "$(date) ${1:-missing}" >> $msglog
}

if [ -f $lock ]; then
        log "Already run, exiting..."
else
        > $lock
        dir="pole-talents.fr/htdocs"
        git -C ~/$dir remote update &> /dev/null
        checkgit=`git -C ~/$dir status`
        if [[ ! "$checkgit" =~ "Your branch is up-to-date" ]]; then
                log "------------ Update PROD ------------"
                git -C ~/$dir pull &>> $msglog
                /usr/local/bin/gulp --cwd $dir deploy --prod &>> $msglog
                log "-------------------------------------"
        fi
        rm $lock

fi
exit 0
